# Generated by Django 5.0.6 on 2025-10-17 13:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Mês/competência da fatura (ex.: 2025-01-01)')),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='matriculas.matricula')),
            ],
            options={
                'ordering': ['-competencia', '-id'],
                'unique_together': {('matricula', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='financeiro.fatura')),
            ],
        ),
    ]
