# Generated by Django 5.0.6 on 2025-10-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropostaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.turma')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='matriculas.planomensalidade')),
            ],
            options={
                'unique_together': {('aluno', 'turma', 'ano_letivo')},
            },
        ),
    ]
