# Generated by Django 5.0.6 on 2025-10-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'PROFESSOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aula',
            name='alocacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='academico.alocacao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='academico.disciplina'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.avaliacao'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.aluno'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='academico.aula'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'PROFESSOR'}, related_name='turmas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='academico.serie'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='academico.turma'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='academico.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('alocacao', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('avaliacao', 'aluno')},
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('aula', 'aluno')},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'serie', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('turma', 'disciplina', 'titulo', 'data')},
        ),
        migrations.AlterUniqueTogether(
            name='alocacao',
            unique_together={('turma', 'disciplina', 'professor')},
        ),
    ]
